Deliverable: Clean repo, non-reproducible environment
Unable to create venv.

Problem:
Error: [WinError 2] The system cannot find the file specified

Solution:
Unable to change organisation permissions. Need to change permissions before attempting venv again.
Currently, installed pandas without venv.